### ISSUE TITLE
Error in allel.VariantChunkedTable on hdf5

### ISSUE THREAD

**Issue by Homap** [cggh/scikit-allel#280]
Hello,

Thank you very much for the amazing package.

I've been following your tutorial on "A tour of scikit-allel" using my own data. However, I get to a problem when using `allel.VariantChunkedTable` on the `hdf5 `file.

These are my commands:
`callset_fn = allel.vcf_to_hdf5('three_species_got_shared_cpg_annotated.chrompos.vcf', 'shared_snps_got.h5', fields='*', overwrite=True)`

`callset = h5py.File('shared_snps_got.h5', mode='r')`
`chrom = 'Chr3'`
```
variants = allel.VariantChunkedTable(callset[chrom]['variants'],
                                    names = ['POS', 'REF', 'ALT', 'DP', 'MQ', 'QD', 'num_alleles'],
                                    index = 'POS')
```
I get a key error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-33-c9fe6cf74c23> in <module>()
      1 # Visualize variant density
----> 2 variants = allel.VariantChunkedTable(callset[chrom]['variants'],
      3                                     names = ['POS', 'REF', 'ALT', 'DP', 'MQ', 'QD', 'num_alleles'],
      4                                     index = 'POS')

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
~/miniconda3/lib/python3.6/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    260                 raise ValueError("Invalid HDF5 object reference")
    261         else:
--> 262             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    263 
    264         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/h5o.pyx in h5py.h5o.open()
KeyError: "Unable to open object (object 'Chr3' doesn't exist)"

```
I assume there is sthg about using HDF5 that I don't understand. In the tutorial, you pick a chromosome arm to work with `3L`so I just took one of my chromosomes `Chr3` as it is stated in the `CHROM`field. I'd appreciate your help very much.

Thank you in advance,
Kind regards,
Homa

**Comment by hardingnj** [comment]
Hi there,

I suspect this is a naming issue. Can you share the output of
```
list(callset.keys())
```

Also, there is a scikit-allel google group to address user questions, and you may get a quicker response than via this issue tracker. 

Also, we encourage the use of `zarr` rather than `hdf5`, via `vcf_to_zarr`. It has a few advantages, including the very handy `callset.tree()` method that allows you to see interactively what groups/datasets your data contains.

**Comment by Homap** [comment]
Thank you very much for your reply.

`list(callset.keys())`
`['calldata', 'samples', 'variants']`

Definitely, I will use `zarr `as well and will post on scikit-allel google group for next questions.

**Comment by Homap** [comment]
I could solve it with the following command:

```
variants = allel.VariantChunkedTable(callset['variants'],
                                  names = ['CHROM', 'POS', 'REF', 'ALT', 'DP', 'MQ', 'QD'])
```

**Comment by hardingnj** [comment]
If you have a good reason to use `hdf5` then that's completely fine- R compatibility is nice. 

The issue here is that the group hasn't been created at the level of the chromosome. 

I would suggest using the `group` and `region` arguments to `vcf_to_hdf5`, and looping through all chromosomes in your file.

**Comment by Homap** [comment]
Thank you so much!

I need to learn more about HDF5. I just used `HDFCompress` to visualise my HDF5 file. I see now! I will create group at the level of chromosome. Really cool! Thanks again!
