### ISSUE TITLE
vcf to hdf5 tabix warning

### ISSUE THREAD

**Issue by Homap** [cggh/scikit-allel#292]
Hello,

Thank you for the wonderful package.

When trying to convert vcf to hdf5, using the following:

```
chr_l = ['chr1','chr2','chr3','chr4','chr5','chr6','chr7','chr8','chr9','chr10',
'chr11','chr12','chr13','chr14','chr15','chr17','chr18','chr19','chr20','chr21',
'chr22','chr23','chr24','chr25','chr26','chr27','chr28','chr1A','chrLGE22','chrZ']
for element in chr_l:
	allel.vcf_to_hdf5('../data/file.vcf.gz', "../data/file.h5.gz", compression='gzip', fields='*', overwrite=True, region=element, group=element)

```
I get the following warning:
```
/pathto/envs/popgene/lib/python3.7/site-packages/allel/io/vcf_read.py:1051: UserWarning: tabix not found, falling back to scanning to region
  warnings.warn('tabix not found, falling back to scanning to region')
```
I was wondering what does this mean and how I could solve it?

Thank you!

**Comment by alimanfoo** [comment]
Hi @Homap,

```
UserWarning: tabix not found, falling back to scanning to region
  warnings.warn('tabix not found, falling back to scanning to region')
```

This means that tabix is not installed on the system you are running on, which means that scikit-allel has to scan through the VCF to find the data for a given chromosome, which can be slow. If you are able to install tabix then it will be faster, because scikit-allel can use tabix to jump into the VCF file to the location where the data are for a given chromosome.

If you are on windows then there is no way to install tabix. If you are on linux or max then you can install tabix various ways, e.g., via bioconda (I think it's part of the htslib package).

Hth.

**Comment by Homap** [comment]
Hi, 

Thank you so much. I installed `tabix `via bionconda and it's now under:

`/pathto/envs/popgene/bin/tabix`

I tried again, and I got almost the same warning:
```
/pathto/envs/popgene/lib/python3.7/site-packages/allel/io/vcf_read.py:1057: UserWarning: error occurred attempting tabix ([tabix] failed to load the index file.); falling back to scanning to region
  'scanning to region' % e)
```
Thanks a lot for your help!
Homa

**Comment by alimanfoo** [comment]
Hi Homa, now you need to tabix index your VCF file. E.g., if I remember
rightly, run:

tabix -p vcf /path/to/your/file.vcf.gz

That should create an index file. Then scikit-allel warning should go away.
