### ISSUE TITLE
High multi-allelic variants

### ISSUE THREAD

**Issue by shubhamsaini** [cggh/scikit-allel#304]
I am working with variants, where the number of alternate alleles can go upto 15. scikit-allel only reads first 3 alt alleles in callset['calldata/ALT'], and ignores all other alleles. How can I read information for all ALT alleles?

**Comment by alimanfoo** [comment]
Hi @shubhamsaini, you can increase the number of alternate alleles that are read. The relevant parameter is ``alt_number``. There is an example of usage on [my blog](http://alimanfoo.github.io/2017/06/14/read-vcf.html#number-of-alternate-alleles). You can pass this parameter to any of the VCF parsing functions, e.g., [read_vcf](http://alimanfoo.github.io/2017/06/14/read-vcf.html#number-of-alternate-alleles) or [vcf_to_zarr](https://scikit-allel.readthedocs.io/en/latest/io.html#allel.vcf_to_zarr). Hth.

**Comment by shubhamsaini** [comment]
Thanks. Is there any way to automatically detect the `alt_number`? I basically need all the alleles in the `callset['calldata/ALT']` variable.

**Comment by hardingnj** [comment]
If you really don't know the max ALTs to expect you could try counting the number of commas in your ALT field of the vcf (and adding one).
`zgrep -v "^#" file.vcf.gz | cut -f5 | sed 's/[^,]//g' | awk '{print length}' | awk 'n < $0 {n=$0}END{print n}'`

(Closing because above comment addressed issue.)
