### ISSUE TITLE
GenotypeArray.subset improve argument type inference

### ISSUE THREAD

**Issue by travc** [cggh/scikit-allel#55]
```
g = allel.GenotypeArray([[[0, 0, 0], [0, 0, 1]],
                         [[0, 1, 1], [1, 1, 1]],
                         [[0, 1, 2], [-1, -1, -1]]],
                        dtype='i1')

print('slicing: ', g[:,[0]])
print('subset:', g.subset(range(g.n_variants), [0]))
```

```
slicing:
[[[0 0 0]]
 [[0 1 1]]
 [[0 1 2]]]

subset:
[[[0 1 1]]
 [[0 1 2]]]
```

**Comment by alimanfoo** [comment]
What's happening here is that the variant selection (ie range(n_variants))
has the same length as the genotype array, so scikit-allel assumes it is a
Boolean selection rather than a list of indices. The first value is 0
(false) hence the first row is dropped.

The subset function is trying to be flexible and accommodate either indices
or Boolean selections. Maybe the current logic for inferring which type of
argument has been providided should be revised, to avoid the mistake where
a list of indices as long as the axis being selected has been passed.

On Wednesday, 13 January 2016, Travis Collier <notifications@github.com>
wrote:

> g = allelGenotypeArray([[[0, 0, 0], [0, 0, 1]],
>                          [[0, 1, 1], [1, 1, 1]],
>                          [[0, 1, 2], [-1, -1, -1]]],
>                         dtype='i1')
>
> print('slicing: ', g[:,[0]])
> print('subset:', gsubset(range(gn_variants), [0]))
>
> slicing:
> [[[0 0 0]]
>  [[0 1 1]]
>  [[0 1 2]]]
>
> subset:
> [[[0 1 1]]
>  [[0 1 2]]]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cggh/scikit-allel/issues/55>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
I think I will make a change here, to explicitly detect boolean arrays, rather than relying on the length of the array, to infer argument type.

**Comment by travc** [comment]
It might be nice to handle None for the positions argument to just subset by samples (include all positions).  There may even be a more efficient implementation for that case.
